<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="2" failed="0" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-04-29T14:32:12 IST" name="Default suite" finished-at="2025-04-29T14:32:12 IST" duration-ms="103">
    <groups>
    </groups>
    <test started-at="2025-04-29T14:32:12 IST" name="Default test" finished-at="2025-04-29T14:32:12 IST" duration-ms="103">
      <class name="com.framework.utils.ExceptionTest">
        <test-method signature="testDivideByZeroException()[pri:0, instance:com.framework.utils.ExceptionTest@3c77d488]" started-at="2025-04-29T14:32:12 IST" name="testDivideByZeroException" finished-at="2025-04-29T14:32:12 IST" duration-ms="8" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDivideByZeroException -->
        <test-method signature="testNullPointerMessage()[pri:0, instance:com.framework.utils.ExceptionTest@3c77d488]" started-at="2025-04-29T14:32:12 IST" name="testNullPointerMessage" finished-at="2025-04-29T14:32:12 IST" duration-ms="45" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testNullPointerMessage -->
      </class> <!-- com.framework.utils.ExceptionTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
